-g
-w 2
-I "C:\Program Files\AccemicMDE2_2SK\Samples\16LX\CommonInclude"
-I "C:Program Files\AccemicMDE2_2SK\Samples\16LC\CommonInclude"
-linf ON
-lsrc ON
-lsec ON
-lcros OFF
-linc ON
-lexp OBJ
-pl 60
-pw 100
-tab 8
-cwno
-cpu MB90F387
